azs:
- cloud_properties:
    availability_zone: us-west-2a
  name: z1
- cloud_properties:
    availability_zone: us-west-2b
  name: z2
- cloud_properties:
    availability_zone: us-west-2c
  name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 5
disk_types:
- cloud_properties:
    type: gp2
  disk_size: 3000
  name: default
- cloud_properties:
    type: gp2
  disk_size: 50000
  name: large
- cloud_properties:
    type: gp2
  disk_size: 50000
  name: bosh
- cloud_properties:
    type: gp3
  disk_size: 10240
  name: concourse
exodus:
  bosh: uswest2demo
  dated: 2022-07-22 03:20:03 +0000
  deployer: unknown
  features: ""
  is_director: false
  kit_is_dev: false
  kit_name: jumpbox
  kit_version: 1.3.2
  use_create_env: false
  vault_base: /secret/uswest2demo/a/jumpbox
  version: 2.8.4
genesis:
  bosh_env: uswest2demo
  ci_mount: /secret/ci/
  env: uswest2demo-a
  exodus_mount: /secret/exodus/
  exodus_path: uswest2demo-a/jumpbox
  min_version: 2.7.11
  secrets_mount: /secret/
  secrets_path: uswest2demo/a/jumpbox
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: jumpbox
    properties:
      jumpbox:
        banner: null
        bashrc: null
        env:
          TMPDIR: /var/vcap/data/root_tmp
        hostname: uswest2demo-a-jumpbox
        hosts: []
        users:
        - name: cweibel
          shell: /bin/bash
          ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+m//AHyfHcgTenRoDTRkpyK33ZN7+xZZCHDcFW92DUeIdZL78+u5CiEIgYskwzJXl1GbrVXcKvKEVR9AYO8kCtmRwqQKDPNUeOkMoBVhrOvz/AeUqFI7RyyU77BfTooVtvlRrtsIODDyEwFLcnMq3O5REMfxDwCrxmXarNfMo01UPiz3+14W0XJ4i4qvFDF3wZ8eDSQbGLMHIzcGMnE53YIZgFonvYGvoWnkYR0AGoS7owxBNqi0xrPATo01TZ5UWhqKhmrMHz8aIbgHNOC9PfkqrDkkGLiPzcChJW9a0xP4N+EJlmJTw71A9F2uYgwC5uy8STYvEucXZ8BbMekGYY06xloIpZbgNPoHeRDviO273urXvytUQoj3FO1M4PMQqYa3Fw4E0GsO8NFdab4qmp3gSbQ3ZsrcE09zIExN9Wa5FARWTvz2UAZ2gxHjLZYZMRpzi2SIwfsXSNiIjjZA8wsX+B0iFWW9diFpcmKUs9tHd3OXNSEjBFyk9+aS10iM=
            cweibel@cweibel-mbp
        - name: xgao
          shell: /bin/bash
          ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5u6oGXFP92HF25u4ZTVN5OE6QZQUsglK0LZZU2y2aaOgwJTo7xKP8R9aisXiNx0mOExpA24cS8M+L/aPr6NhZzUaR68/ZMLyVGlAT+9ND5hq0Q2KspH5lc3JBvEz7Mmul2MSoCf9Xf3vsLqyeRLLoVbRwMTsk66XAVrforAvSmSXhuSVQzaEqLpxFXH8sXZTe0OpIEacI/e8W9WA/TEFlnb2wm54vF8OsgC85sKPqHt3w2L6f+/AoqGl//AQHuz+/37TkCA6hspuhGxcTD12bcE3JB2hcKg25ElxWr6WJIRW+NzaXJNeiTKO3Xdi5BT0SQVRo9+VPMtv0dcUljOwhTYHFHtnXPzCnq1QfbDJOfP7l/7EPqjJQ9ce3H/PPHxdcOwrhZEqKAfpOFsgH96K9ILKIL4CfXDAGtMtZNCT+1Bg3KQa0LhODmiltUZZ/qxPJ2uUEdoqRpnco6fmevz4AGKbC83UoFtc6tLFdouQqgLOr/fO219xY5o0p322XfAaQPIFQgTz/15ngLsJniPxjAyCwaGdANkIfWju39El5mwYW+Wh8reEjos64DxX3earbSv2ndzpLH1jecbqEJL5KVqk5cBP5qrb5jqW0OBX9Y2use2qdmuwnelwdiOFfvvT+eRAYOjHL0bs5Lz8Rd3vcSJsyqnEqkppJ80mw9LMY3Q==
            gaoxiujiao@gmal.com
    release: jumpbox
  - name: inventory
    release: jumpbox
  - name: toolbelt
    release: toolbelt
  - name: toolbelt-quick
    release: toolbelt
  name: jumpbox
  networks:
  - name: default
    static_ips:
    - 10.4.1.10
  persistent_disk_type: default
  stemcell: default
  vm_type: default
kit:
  features: []
  name: jumpbox
  version: 1.3.2
meta:
  default:
    azs:
    - z1
  vault: /secret/uswest2demo/a/jumpbox
name: uswest2demo-a-jumpbox
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.5
    static:
    - 10.4.1.6-10.4.1.16
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.5
    static:
    - 10.4.2.6-10.4.2.16
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.5
    static:
    - 10.4.3.6-10.4.3.16
  type: manual
- name: concourse
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.99
    static:
    - 10.4.1.100-10.4.1.106
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.99
    static:
    - 10.4.2.100-10.4.2.106
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.99
    static:
    - 10.4.3.100-10.4.3.106
  type: manual
- name: concourse-full
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.99
    static:
    - 10.4.1.150-10.4.1.156
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.99
    static:
    - 10.4.2.150-10.4.2.156
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.99
    static:
    - 10.4.3.150-10.4.3.156
  type: manual
- name: dev
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0ea631cc3ad19e04f
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.16.1
    range: 10.4.16.0/24
    reserved:
    - 10.4.16.0-10.4.16.3
    static:
    - 10.4.16.4-10.4.16.16
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-09a05edb82702379b
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.17.1
    range: 10.4.17.0/24
    reserved:
    - 10.4.17.0-10.4.17.3
    static:
    - 10.4.17.4-10.4.17.16
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0dd034854c197dc41
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.18.1
    range: 10.4.18.0/24
    reserved:
    - 10.4.18.0-10.4.18.3
    static:
    - 10.4.18.4-10.4.18.16
  type: manual
- name: baby
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-064b78e587e3b8bf5
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.63.1
    range: 10.4.63.0/24
    reserved:
    - 10.4.63.0-10.4.63.3
    static:
    - 10.4.63.4-10.4.63.6
  type: manual
params:
  banner: null
  bashrc: null
  ca_validity_period: 1y
  cert_validity_period: 180d
  env_vars: {}
  hostname: uswest2demo-a-jumpbox
  hosts: []
  jumpbox_disk_pool: default
  jumpbox_network: default
  jumpbox_static_ip: 10.4.1.10
  jumpbox_vm_type: default
  users:
  - name: cweibel
    shell: /bin/bash
    ssh_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+m//AHyfHcgTenRoDTRkpyK33ZN7+xZZCHDcFW92DUeIdZL78+u5CiEIgYskwzJXl1GbrVXcKvKEVR9AYO8kCtmRwqQKDPNUeOkMoBVhrOvz/AeUqFI7RyyU77BfTooVtvlRrtsIODDyEwFLcnMq3O5REMfxDwCrxmXarNfMo01UPiz3+14W0XJ4i4qvFDF3wZ8eDSQbGLMHIzcGMnE53YIZgFonvYGvoWnkYR0AGoS7owxBNqi0xrPATo01TZ5UWhqKhmrMHz8aIbgHNOC9PfkqrDkkGLiPzcChJW9a0xP4N+EJlmJTw71A9F2uYgwC5uy8STYvEucXZ8BbMekGYY06xloIpZbgNPoHeRDviO273urXvytUQoj3FO1M4PMQqYa3Fw4E0GsO8NFdab4qmp3gSbQ3ZsrcE09zIExN9Wa5FARWTvz2UAZ2gxHjLZYZMRpzi2SIwfsXSNiIjjZA8wsX+B0iFWW9diFpcmKUs9tHd3OXNSEjBFyk9+aS10iM=
      cweibel@cweibel-mbp
  - name: xgao
    shell: /bin/bash
    ssh_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5u6oGXFP92HF25u4ZTVN5OE6QZQUsglK0LZZU2y2aaOgwJTo7xKP8R9aisXiNx0mOExpA24cS8M+L/aPr6NhZzUaR68/ZMLyVGlAT+9ND5hq0Q2KspH5lc3JBvEz7Mmul2MSoCf9Xf3vsLqyeRLLoVbRwMTsk66XAVrforAvSmSXhuSVQzaEqLpxFXH8sXZTe0OpIEacI/e8W9WA/TEFlnb2wm54vF8OsgC85sKPqHt3w2L6f+/AoqGl//AQHuz+/37TkCA6hspuhGxcTD12bcE3JB2hcKg25ElxWr6WJIRW+NzaXJNeiTKO3Xdi5BT0SQVRo9+VPMtv0dcUljOwhTYHFHtnXPzCnq1QfbDJOfP7l/7EPqjJQ9ce3H/PPHxdcOwrhZEqKAfpOFsgH96K9ILKIL4CfXDAGtMtZNCT+1Bg3KQa0LhODmiltUZZ/qxPJ2uUEdoqRpnco6fmevz4AGKbC83UoFtc6tLFdouQqgLOr/fO219xY5o0p322XfAaQPIFQgTz/15ngLsJniPxjAyCwaGdANkIfWju39El5mwYW+Wh8reEjos64DxX3earbSv2ndzpLH1jecbqEJL5KVqk5cBP5qrb5jqW0OBX9Y2use2qdmuwnelwdiOFfvvT+eRAYOjHL0bs5Lz8Rd3vcSJsyqnEqkppJ80mw9LMY3Q==
      gaoxiujiao@gmal.com
releases:
- name: jumpbox
  sha1: 7f989d74cf0cbb5192541a2e95c33acc6b999966
  url: https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.9.1/jumpbox-4.9.1.tgz
  version: 4.9.1
- name: toolbelt
  sha1: a36d826fd83ad4c35d767e244eca7a863df02720
  url: https://bosh.io/d/github.com/cloudfoundry-community/toolbelt-boshrelease?v=3.5.1
  version: 3.5.1
stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 4
  serial: false
  update_watch_time: 1000-60000
vm_types:
- cloud_properties:
    ephemeral_disk:
      size: 3000
      type: gp2
    instance_type: t2.small
  name: default
- cloud_properties:
    ephemeral_disk:
      size: 30000
      type: gp2
    instance_type: t3.large
  name: large
- cloud_properties:
    ephemeral_disk:
      size: 25000
      type: gp2
    instance_type: t3.medium
  name: bosh
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp3
    instance_type: t3.large
  name: concourse
- cloud_properties:
    ephemeral_disk:
      size: 65536
      type: gp3
    instance_type: t3.medium
  name: concourse-worker